/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CompetitionRegistry } from "./CompetitionRegistry";
export * as factories from "./factories";
export { CompetitionRegistry__factory } from "./factories/CompetitionRegistry__factory";
