/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardStrategyRouteImport } from './routes/dashboard.strategy'
import { Route as DashboardGuardrailsRouteImport } from './routes/dashboard.guardrails'
import { Route as DashboardActivityRouteImport } from './routes/dashboard.activity'
import { Route as ApiAgentDecideRouteImport } from './routes/api/agent/decide'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStrategyRoute = DashboardStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuardrailsRoute = DashboardGuardrailsRouteImport.update({
  id: '/guardrails',
  path: '/guardrails',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAgentDecideRoute = ApiAgentDecideRouteImport.update({
  id: '/api/agent/decide',
  path: '/api/agent/decide',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/guardrails': typeof DashboardGuardrailsRoute
  '/dashboard/strategy': typeof DashboardStrategyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/agent/decide': typeof ApiAgentDecideRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/guardrails': typeof DashboardGuardrailsRoute
  '/dashboard/strategy': typeof DashboardStrategyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/agent/decide': typeof ApiAgentDecideRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/guardrails': typeof DashboardGuardrailsRoute
  '/dashboard/strategy': typeof DashboardStrategyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/agent/decide': typeof ApiAgentDecideRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dashboard/activity'
    | '/dashboard/guardrails'
    | '/dashboard/strategy'
    | '/dashboard/'
    | '/api/agent/decide'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/activity'
    | '/dashboard/guardrails'
    | '/dashboard/strategy'
    | '/dashboard'
    | '/api/agent/decide'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dashboard/activity'
    | '/dashboard/guardrails'
    | '/dashboard/strategy'
    | '/dashboard/'
    | '/api/agent/decide'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiAgentDecideRoute: typeof ApiAgentDecideRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/strategy': {
      id: '/dashboard/strategy'
      path: '/strategy'
      fullPath: '/dashboard/strategy'
      preLoaderRoute: typeof DashboardStrategyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guardrails': {
      id: '/dashboard/guardrails'
      path: '/guardrails'
      fullPath: '/dashboard/guardrails'
      preLoaderRoute: typeof DashboardGuardrailsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/agent/decide': {
      id: '/api/agent/decide'
      path: '/api/agent/decide'
      fullPath: '/api/agent/decide'
      preLoaderRoute: typeof ApiAgentDecideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardGuardrailsRoute: typeof DashboardGuardrailsRoute
  DashboardStrategyRoute: typeof DashboardStrategyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardGuardrailsRoute: DashboardGuardrailsRoute,
  DashboardStrategyRoute: DashboardStrategyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiAgentDecideRoute: ApiAgentDecideRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
