/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardStrategyRouteImport } from './routes/dashboard.strategy'
import { Route as DashboardGuardrailsRouteImport } from './routes/dashboard.guardrails'
import { Route as DashboardActivityRouteImport } from './routes/dashboard.activity'
import { Route as ApiSignalsRouteImport } from './routes/api/signals'
import { Route as ApiTwakSwapRouteImport } from './routes/api/twak/swap'
import { Route as ApiTwakRegisterRouteImport } from './routes/api/twak/register'
import { Route as ApiTwakPingRouteImport } from './routes/api/twak/ping'
import { Route as ApiTwakBalanceRouteImport } from './routes/api/twak/balance'
import { Route as ApiChainTxsRouteImport } from './routes/api/chain/txs'
import { Route as ApiBnbContextRouteImport } from './routes/api/bnb/context'
import { Route as ApiAgentDecideRouteImport } from './routes/api/agent/decide'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStrategyRoute = DashboardStrategyRouteImport.update({
  id: '/strategy',
  path: '/strategy',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuardrailsRoute = DashboardGuardrailsRouteImport.update({
  id: '/guardrails',
  path: '/guardrails',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardActivityRoute = DashboardActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiSignalsRoute = ApiSignalsRouteImport.update({
  id: '/api/signals',
  path: '/api/signals',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwakSwapRoute = ApiTwakSwapRouteImport.update({
  id: '/api/twak/swap',
  path: '/api/twak/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwakRegisterRoute = ApiTwakRegisterRouteImport.update({
  id: '/api/twak/register',
  path: '/api/twak/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwakPingRoute = ApiTwakPingRouteImport.update({
  id: '/api/twak/ping',
  path: '/api/twak/ping',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTwakBalanceRoute = ApiTwakBalanceRouteImport.update({
  id: '/api/twak/balance',
  path: '/api/twak/balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChainTxsRoute = ApiChainTxsRouteImport.update({
  id: '/api/chain/txs',
  path: '/api/chain/txs',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBnbContextRoute = ApiBnbContextRouteImport.update({
  id: '/api/bnb/context',
  path: '/api/bnb/context',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAgentDecideRoute = ApiAgentDecideRouteImport.update({
  id: '/api/agent/decide',
  path: '/api/agent/decide',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/signals': typeof ApiSignalsRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/guardrails': typeof DashboardGuardrailsRoute
  '/dashboard/strategy': typeof DashboardStrategyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/agent/decide': typeof ApiAgentDecideRoute
  '/api/bnb/context': typeof ApiBnbContextRoute
  '/api/chain/txs': typeof ApiChainTxsRoute
  '/api/twak/balance': typeof ApiTwakBalanceRoute
  '/api/twak/ping': typeof ApiTwakPingRoute
  '/api/twak/register': typeof ApiTwakRegisterRoute
  '/api/twak/swap': typeof ApiTwakSwapRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/signals': typeof ApiSignalsRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/guardrails': typeof DashboardGuardrailsRoute
  '/dashboard/strategy': typeof DashboardStrategyRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/agent/decide': typeof ApiAgentDecideRoute
  '/api/bnb/context': typeof ApiBnbContextRoute
  '/api/chain/txs': typeof ApiChainTxsRoute
  '/api/twak/balance': typeof ApiTwakBalanceRoute
  '/api/twak/ping': typeof ApiTwakPingRoute
  '/api/twak/register': typeof ApiTwakRegisterRoute
  '/api/twak/swap': typeof ApiTwakSwapRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/api/signals': typeof ApiSignalsRoute
  '/dashboard/activity': typeof DashboardActivityRoute
  '/dashboard/guardrails': typeof DashboardGuardrailsRoute
  '/dashboard/strategy': typeof DashboardStrategyRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/agent/decide': typeof ApiAgentDecideRoute
  '/api/bnb/context': typeof ApiBnbContextRoute
  '/api/chain/txs': typeof ApiChainTxsRoute
  '/api/twak/balance': typeof ApiTwakBalanceRoute
  '/api/twak/ping': typeof ApiTwakPingRoute
  '/api/twak/register': typeof ApiTwakRegisterRoute
  '/api/twak/swap': typeof ApiTwakSwapRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/api/signals'
    | '/dashboard/activity'
    | '/dashboard/guardrails'
    | '/dashboard/strategy'
    | '/dashboard/'
    | '/api/agent/decide'
    | '/api/bnb/context'
    | '/api/chain/txs'
    | '/api/twak/balance'
    | '/api/twak/ping'
    | '/api/twak/register'
    | '/api/twak/swap'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/signals'
    | '/dashboard/activity'
    | '/dashboard/guardrails'
    | '/dashboard/strategy'
    | '/dashboard'
    | '/api/agent/decide'
    | '/api/bnb/context'
    | '/api/chain/txs'
    | '/api/twak/balance'
    | '/api/twak/ping'
    | '/api/twak/register'
    | '/api/twak/swap'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/api/signals'
    | '/dashboard/activity'
    | '/dashboard/guardrails'
    | '/dashboard/strategy'
    | '/dashboard/'
    | '/api/agent/decide'
    | '/api/bnb/context'
    | '/api/chain/txs'
    | '/api/twak/balance'
    | '/api/twak/ping'
    | '/api/twak/register'
    | '/api/twak/swap'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ApiSignalsRoute: typeof ApiSignalsRoute
  ApiAgentDecideRoute: typeof ApiAgentDecideRoute
  ApiBnbContextRoute: typeof ApiBnbContextRoute
  ApiChainTxsRoute: typeof ApiChainTxsRoute
  ApiTwakBalanceRoute: typeof ApiTwakBalanceRoute
  ApiTwakPingRoute: typeof ApiTwakPingRoute
  ApiTwakRegisterRoute: typeof ApiTwakRegisterRoute
  ApiTwakSwapRoute: typeof ApiTwakSwapRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/strategy': {
      id: '/dashboard/strategy'
      path: '/strategy'
      fullPath: '/dashboard/strategy'
      preLoaderRoute: typeof DashboardStrategyRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guardrails': {
      id: '/dashboard/guardrails'
      path: '/guardrails'
      fullPath: '/dashboard/guardrails'
      preLoaderRoute: typeof DashboardGuardrailsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/activity': {
      id: '/dashboard/activity'
      path: '/activity'
      fullPath: '/dashboard/activity'
      preLoaderRoute: typeof DashboardActivityRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/signals': {
      id: '/api/signals'
      path: '/api/signals'
      fullPath: '/api/signals'
      preLoaderRoute: typeof ApiSignalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twak/swap': {
      id: '/api/twak/swap'
      path: '/api/twak/swap'
      fullPath: '/api/twak/swap'
      preLoaderRoute: typeof ApiTwakSwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twak/register': {
      id: '/api/twak/register'
      path: '/api/twak/register'
      fullPath: '/api/twak/register'
      preLoaderRoute: typeof ApiTwakRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twak/ping': {
      id: '/api/twak/ping'
      path: '/api/twak/ping'
      fullPath: '/api/twak/ping'
      preLoaderRoute: typeof ApiTwakPingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/twak/balance': {
      id: '/api/twak/balance'
      path: '/api/twak/balance'
      fullPath: '/api/twak/balance'
      preLoaderRoute: typeof ApiTwakBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chain/txs': {
      id: '/api/chain/txs'
      path: '/api/chain/txs'
      fullPath: '/api/chain/txs'
      preLoaderRoute: typeof ApiChainTxsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/bnb/context': {
      id: '/api/bnb/context'
      path: '/api/bnb/context'
      fullPath: '/api/bnb/context'
      preLoaderRoute: typeof ApiBnbContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/agent/decide': {
      id: '/api/agent/decide'
      path: '/api/agent/decide'
      fullPath: '/api/agent/decide'
      preLoaderRoute: typeof ApiAgentDecideRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardActivityRoute: typeof DashboardActivityRoute
  DashboardGuardrailsRoute: typeof DashboardGuardrailsRoute
  DashboardStrategyRoute: typeof DashboardStrategyRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardActivityRoute: DashboardActivityRoute,
  DashboardGuardrailsRoute: DashboardGuardrailsRoute,
  DashboardStrategyRoute: DashboardStrategyRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ApiSignalsRoute: ApiSignalsRoute,
  ApiAgentDecideRoute: ApiAgentDecideRoute,
  ApiBnbContextRoute: ApiBnbContextRoute,
  ApiChainTxsRoute: ApiChainTxsRoute,
  ApiTwakBalanceRoute: ApiTwakBalanceRoute,
  ApiTwakPingRoute: ApiTwakPingRoute,
  ApiTwakRegisterRoute: ApiTwakRegisterRoute,
  ApiTwakSwapRoute: ApiTwakSwapRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
